package com.civicpulse.entites;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "complaints")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Complaint {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "complaint_number", nullable = false, unique = true)
    private String complaintNumber;

    @Column(nullable = false)
    private String title;

    @Column(columnDefinition = "TEXT")
    private String description;

    private String category;

    private String location;

    private String priority;

    private String status;

    private String department;

    @Column(name = "citizen_name")
    private String citizenName;

    @Column(name = "citizen_contact")
    private String citizenContact;

    @Column(name = "citizen_email")
    private String citizenEmail;

    // =========================================================
    // WORK PROGRESS
    // =========================================================

    @Column(name = "progress_update", columnDefinition = "TEXT")
    private String progressUpdate;


    // =========================================================
    // AI PRIORITY ASSESSMENT
    // =========================================================

    /*
     * AI suggested priority.
     *
     * Possible values:
     * LOW
     * MEDIUM
     * HIGH
     * CRITICAL
     */
    @Column(name = "ai_priority")
    private String aiPriority;

    /*
     * Explanation generated by the AI/rule-based
     * priority assessment system.
     */
    @Column(name = "ai_priority_reason", columnDefinition = "TEXT")
    private String aiPriorityReason;

    /*
     * Confidence percentage of AI prediction.
     *
     * Example:
     * 85
     * means 85% confidence.
     */
    @Column(name = "ai_priority_confidence")
    private Integer aiPriorityConfidence;


    // =========================================================
    // TIMESTAMPS
    // =========================================================

    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    @Column(name = "assigned_at")
    private LocalDateTime assignedAt;

    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    @Column(name = "in_progress_at")
    private LocalDateTime inProgressAt;

    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    @Column(name = "resolved_at")
    private LocalDateTime resolvedAt;


    // =========================================================
    // RESOLUTION / REMARKS
    // =========================================================

    @Column(columnDefinition = "TEXT")
    private String resolution;

    @Column(columnDefinition = "TEXT")
    private String remarks;


    // =========================================================
    // ASSIGNED OFFICER
    // =========================================================

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "assigned_officer_id")
    @JsonIgnoreProperties({
            "assignedComplaints",
            "password",
            "hibernateLazyInitializer",
            "handler"
    })
    private Officer assignedOfficer;


    // =========================================================
    // ATTACHMENTS
    // =========================================================

    @OneToMany(
            mappedBy = "complaint",
            cascade = CascadeType.ALL,
            orphanRemoval = true,
            fetch = FetchType.LAZY
    )
    @JsonIgnoreProperties({
            "complaint",
            "hibernateLazyInitializer",
            "handler"
    })
    private List<ComplaintAttachment> attachments = new ArrayList<>();


    // =========================================================
    // LIFECYCLE CALLBACKS
    // =========================================================

    @PrePersist
    protected void onCreate() {

        if (this.createdAt == null) {
            this.createdAt = LocalDateTime.now();
        }

        this.updatedAt = LocalDateTime.now();
    }


    @PreUpdate
    protected void onUpdate() {

        this.updatedAt = LocalDateTime.now();
    }


    // =========================================================
    // ATTACHMENT HELPER METHODS
    // =========================================================

    public void addAttachment(ComplaintAttachment attachment) {

        attachments.add(attachment);

        attachment.setComplaint(this);
    }


    public void removeAttachment(ComplaintAttachment attachment) {

        attachments.remove(attachment);

        attachment.setComplaint(null);
    }


    // =========================================================
    // GETTERS AND SETTERS
    // =========================================================

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }


    public String getComplaintNumber() {
        return complaintNumber;
    }

    public void setComplaintNumber(String complaintNumber) {
        this.complaintNumber = complaintNumber;
    }


    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }


    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }


    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }


    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }


    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }


    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }


    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }


    public String getCitizenName() {
        return citizenName;
    }

    public void setCitizenName(String citizenName) {
        this.citizenName = citizenName;
    }


    public String getCitizenContact() {
        return citizenContact;
    }

    public void setCitizenContact(String citizenContact) {
        this.citizenContact = citizenContact;
    }


    public String getCitizenEmail() {
        return citizenEmail;
    }

    public void setCitizenEmail(String citizenEmail) {
        this.citizenEmail = citizenEmail;
    }


    // =========================================================
    // WORK PROGRESS GETTERS / SETTERS
    // =========================================================

    public String getProgressUpdate() {
        return progressUpdate;
    }

    public void setProgressUpdate(String progressUpdate) {
        this.progressUpdate = progressUpdate;
    }


    // =========================================================
    // AI PRIORITY GETTERS / SETTERS
    // =========================================================

    public String getAiPriority() {
        return aiPriority;
    }

    public void setAiPriority(String aiPriority) {
        this.aiPriority = aiPriority;
    }


    public String getAiPriorityReason() {
        return aiPriorityReason;
    }

    public void setAiPriorityReason(String aiPriorityReason) {
        this.aiPriorityReason = aiPriorityReason;
    }


    public Integer getAiPriorityConfidence() {
        return aiPriorityConfidence;
    }

    public void setAiPriorityConfidence(Integer aiPriorityConfidence) {
        this.aiPriorityConfidence = aiPriorityConfidence;
    }


    // =========================================================
    // TIMESTAMP GETTERS / SETTERS
    // =========================================================

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }


    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }


    public LocalDateTime getAssignedAt() {
        return assignedAt;
    }

    public void setAssignedAt(LocalDateTime assignedAt) {
        this.assignedAt = assignedAt;
    }


    public LocalDateTime getInProgressAt() {
        return inProgressAt;
    }

    public void setInProgressAt(LocalDateTime inProgressAt) {
        this.inProgressAt = inProgressAt;
    }


    public LocalDateTime getResolvedAt() {
        return resolvedAt;
    }

    public void setResolvedAt(LocalDateTime resolvedAt) {
        this.resolvedAt = resolvedAt;
    }


    // =========================================================
    // RESOLUTION / REMARKS GETTERS / SETTERS
    // =========================================================

    public String getResolution() {
        return resolution;
    }

    public void setResolution(String resolution) {
        this.resolution = resolution;
    }


    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }


    // =========================================================
    // OFFICER GETTERS / SETTERS
    // =========================================================

    public Officer getAssignedOfficer() {
        return assignedOfficer;
    }

    public void setAssignedOfficer(Officer assignedOfficer) {
        this.assignedOfficer = assignedOfficer;
    }


    // =========================================================
    // ATTACHMENT GETTERS / SETTERS
    // =========================================================

    public List<ComplaintAttachment> getAttachments() {
        return attachments;
    }

    public void setAttachments(List<ComplaintAttachment> attachments) {
        this.attachments = attachments;
    }
}